balancer:
  container_name: balancer
  build: ./balancer
  ports:
    - "3000:80"
  links:
    - app1
    - app2

app1:
  container_name: app1
  build: ./app
  expose:
    - "80"
  ports:
    - "2222:22"
  links:
    - database
  env_file:
    - app/.env
  volumes_from:
    - cache

app2:
  container_name: app2
  build: ./static
  expose:
    - "80"
  links:
    - database

cache:
  container_name: cache
  image: busybox
  volumes:
    - /cache

database:
  container_name: postgres
  image: postgres
