balancer:
  container_name: balancer
  build: ./balancer
  ports:
    - "3000:80"
  links:
    - app
  restart: always

app:
  build: ./app
  expose:
    - "80"
  links:
    - database
  env_file:
    - app/.env
  volumes_from:
    - cache

cache:
  container_name: cache
  image: busybox
  volumes:
    - /cache

database:
  container_name: postgres
  image: postgres
